sudo: false
language: rust
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
rust: stable
env:
  global:
  - THERMITE_DEBUG_FILENAME: /tmp/thermite-debug.log
  - T12R_RUBY_VERSION: 2.4.2
matrix:
  include:
  - os: osx
    osx_image: xcode8
  - os: linux
    env: RUBY_STATIC=1
  - os: osx
    osx_image: xcode8.3
    env: RUBY_STATIC=1
  - os: osx
    osx_image: xcode8
    env: RUBY_STATIC=1

cache:
  cargo: true
  directories:
  - $TRAVIS_BUILD_DIR/vendor/bundle

before_install:
- |
  rvm install "$T12R_RUBY_VERSION"
  rvm use "$T12R_RUBY_VERSION"
  if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! which bundle > /dev/null; then
    gem install bundler
  fi
- export LD_LIBRARY_PATH=$(ruby -e 'print RbConfig::CONFIG["libdir"]')
- bundle install --jobs=3 --retry=3 --path=$TRAVIS_BUILD_DIR/vendor/bundle

script:
- bundle exec rake test
- bundle exec rake thermite:tarball
- if [[ -f "$THERMITE_DEBUG_FILENAME" ]]; then cat $THERMITE_DEBUG_FILENAME; fi

deploy:
  provider: releases
  api_key:
    secure: "Jx3MZbcZgkomVsZiQ8ZaJ9Kj36vf7w+lp7ybq0rKcSmimpbujkzxIvSGKtlkH4Mu1O6UDKpydDD36IPPyLCTIZ2aSysc37CesCXOVIrdhhF3x1g3rWywkUvprLux6oBYWAn9evZukEHc8zE6TCG2C30w2rGu8QHMe0ovxF9SG8j68HeqQLQoP9VV7R1gLNWrWTM5Ufcu5pGJbzQsq4o8AyY+sObkMBTJEbOwyHkNqh9qOp6gKF8XmhR9aNjdwQ4gRmyf8rnKtr1iD5NmRlrOVqm999L9zzFjkyPcL1lPveYh6hSch5YjaW9XTAhTrMUBagobzZYfjEUaMXVHEL6tJXyBS+X8f3Bpcc9n1J913GEDferJUsNNhgwdWLz6SYOmBTP9/HQ8sP7fOYumYoSrGeYDZ58FFD1govzTNqOjq3AlFN4oBQWeCnoKYMS55X4NhoaywbbUXQfdJDabgFjbhLpWjCgqi4bo4swy1FEZSesuXrK4bLwZnaeaOu3O6Lez5lQI1ww8W4f8Ag8G6brgf6soQsB4YnM03MmKz5ytUgDNwfiDW7zft7NFpktNjkXpU42r2sksDszfWarUMmKln/E21UKZGMNAJS3XvBIPhkddnNseI8yPtT8X+AdT+tZyiCsGB2sYxiWcsvYWIQuCFKGvrhLE1xTDRsCv1iEAs5U="
  file: t12r-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: data-axle/t12r
    tags: true
