sudo: required
dist: trusty
language: rust
os:
- linux
- osx
rust: stable
env:
  global:
  - THERMITE_DEBUG_FILENAME: /tmp/thermite-debug.log
  matrix:
  - T12R_RUBY_VERSION: 2.3.1

cache:
  cargo: true
  directories:
  - $TRAVIS_BUILD_DIR/vendor/bundle
  - $HOME/.cache/pip

before_install:
- |
  rvm use "$T12R_RUBY_VERSION"
  ruby --version
- bundle install --jobs=3 --retry=3 --path=$TRAVIS_BUILD_DIR/vendor/bundle

before_script:
- |
  export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
  if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! which pip > /dev/null; then
    wget https://bootstrap.pypa.io/get-pip.py
    python get-pip.py --user
  fi
  pip install 'travis-cargo<0.2' --user

script:
- travis-cargo build
- bundle exec rake test
- bundle exec rake thermite:tarball
- if [[ -f "$THERMITE_DEBUG_FILENAME" ]]; then cat $THERMITE_DEBUG_FILENAME; fi

deploy:
  provider: releases
  api_key:
    secure: "RdhUdw/hZ4BTnFbW0VyzoT6xycfshR1kL+c3t82dYxUjnlkhNn7J8MKL8Y27Me8Lvek4tfuumBsVVbaX1G4V+cYG35p1ROxQFnGhb9gbHupiGeeecrziV8QVg80ZDjfo1PXCkGtCfyQa5yfQ2ycUsQA8BXik/B0zKcViAkUWx4Ia+QtW3aw7l2sb4+v0vpjpS82GIscg1uinkdNn7/kWRWcp3Twq22ibD+Z+1gI85DejqafbnKnOAMqz3ikjNzyBW7uORCxmodV+dIbe5zesOgg5FcSbzPQIpn7yixZil1rwrAP+/TyxxatM66Sbw/EqytDPZf2LxIxc1u4ocFT1eyqS1VJVKkRCPI/Hqh1s+3CHg0IkCwibpoh57TCxu5pDjf8KwMPOi5G9htWpqzHW6mRXK2RyE7au0PSAUsMX0DMe99mTODhY5n9yaiyzlZ1CXkGr/cnkLIcZw2dt0nQ/bNZTxCu/1ZJhrKmjEiHpIZj3Os52AauAyaN/kcHiqkdD3WwbDTBlTdV4ooSxm8iTTMXiDQLLdRMO8wiz/doRbc7ymAlwnYMNI2a4BlWPmhZHa1hhudjc8z7a3RK0gpOr5MbdMD+1ihXN0SHM8qaeDrz+y4I2s6durnfx8XtV6pTCq1Sul6SHXcinxiHNmYIMhI7UKlDUCyk4a7q9LZZ7Gxg="
  file: t12r-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: data-axle/t12r
    tags: true
